/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DropMode;
import javax.swing.table.DefaultTableModel;
import model.Dados;
import model.Metodos;

/**
 *
 * @author Lenovo
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
     Dados[] total;
    
    
     public Tela() {
        total =  Dados.vetorDados();
        initComponents();
        montaTabela(total);
    }
    
     private void montaTabela(Dados[] lista){
        tbTabela.setModel(Dados.getTableModel(lista));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btNome = new javax.swing.JButton();
        btData = new javax.swing.JButton();
        btEstado = new javax.swing.JButton();
        btMunicipio = new javax.swing.JButton();
        btDiasSemChuva = new javax.swing.JButton();
        btPrecipitacao = new javax.swing.JButton();
        btRiscoDeFogo = new javax.swing.JButton();
        btFrp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbDados.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDados.setText("Dados de satélite do pantanal");

        tbTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Data", "Estado", "Município", "Dias Sem Chuva", "Precipitação", "Risco de Fogo", "Latitude", "Longitude", "FRP"
            }
        ));
        jScrollPane1.setViewportView(tbTabela);

        btNome.setText("Nome");
        btNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNomeActionPerformed(evt);
            }
        });

        btData.setText("Data");
        btData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDataActionPerformed(evt);
            }
        });

        btEstado.setText("Estado");
        btEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstadoActionPerformed(evt);
            }
        });

        btMunicipio.setText("Município");
        btMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMunicipioActionPerformed(evt);
            }
        });

        btDiasSemChuva.setText("Dias Sem Chuva");
        btDiasSemChuva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDiasSemChuvaActionPerformed(evt);
            }
        });

        btPrecipitacao.setText("Precipitação");
        btPrecipitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrecipitacaoActionPerformed(evt);
            }
        });

        btRiscoDeFogo.setText("Risco de Fogo");
        btRiscoDeFogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRiscoDeFogoActionPerformed(evt);
            }
        });

        btFrp.setText("FRP");
        btFrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMunicipio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDiasSemChuva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPrecipitacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRiscoDeFogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFrp)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNome)
                    .addComponent(btData)
                    .addComponent(btEstado)
                    .addComponent(btMunicipio)
                    .addComponent(btDiasSemChuva)
                    .addComponent(btPrecipitacao)
                    .addComponent(btRiscoDeFogo)
                    .addComponent(btFrp))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDados)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNomeActionPerformed
        // TODO add your handling code here:
        System.out.println("Tempo gasto: " + Metodos.quickSatelite(total));
        tbTabela.setModel(new DefaultTableModel());
        montaTabela(total);
    }//GEN-LAST:event_btNomeActionPerformed

    private void btDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDataActionPerformed
        // TODO add your handling code here:
        System.out.println("Tempo gasto: " + Metodos.quickData(total));
        tbTabela.setModel(new DefaultTableModel());
        montaTabela(total);
    }//GEN-LAST:event_btDataActionPerformed

    private void btEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstadoActionPerformed
        // TODO add your handling code here:
        System.out.println("Tempo gasto: " + Metodos.quickEstado(total));
        tbTabela.setModel(new DefaultTableModel());
        montaTabela(total);
    }//GEN-LAST:event_btEstadoActionPerformed

    private void btMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMunicipioActionPerformed
        // TODO add your handling code here:
        System.out.println("Tempo gasto: " + Metodos.quickMunicipio(total));
        tbTabela.setModel(new DefaultTableModel());
        montaTabela(total);
    }//GEN-LAST:event_btMunicipioActionPerformed

    private void btDiasSemChuvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDiasSemChuvaActionPerformed
        // TODO add your handling code here:
        System.out.println("Tempo gasto: " + Metodos.quickDiasSemChuva(total));
        tbTabela.setModel(new DefaultTableModel());
        montaTabela(total);
    }//GEN-LAST:event_btDiasSemChuvaActionPerformed

    private void btPrecipitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrecipitacaoActionPerformed
        // TODO add your handling code here:
        System.out.println("Tempo gasto: " + Metodos.quickPrecipitacao(total));
        tbTabela.setModel(new DefaultTableModel());
        montaTabela(total);
    }//GEN-LAST:event_btPrecipitacaoActionPerformed

    private void btRiscoDeFogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRiscoDeFogoActionPerformed
        // TODO add your handling code here:
        System.out.println("Tempo gasto: " + Metodos.quickRiscoDeFogo(total));
        tbTabela.setModel(new DefaultTableModel());
        montaTabela(total);
    }//GEN-LAST:event_btRiscoDeFogoActionPerformed

    private void btFrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrpActionPerformed
        // TODO add your handling code here:
        System.out.println("Tempo gasto: " + Metodos.quickFrp(total));
        tbTabela.setModel(new DefaultTableModel());
        montaTabela(total);
    }//GEN-LAST:event_btFrpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btData;
    private javax.swing.JButton btDiasSemChuva;
    private javax.swing.JButton btEstado;
    private javax.swing.JButton btFrp;
    private javax.swing.JButton btMunicipio;
    private javax.swing.JButton btNome;
    private javax.swing.JButton btPrecipitacao;
    private javax.swing.JButton btRiscoDeFogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDados;
    private javax.swing.JTable tbTabela;
    // End of variables declaration//GEN-END:variables
}
